version: "3.8"

services:
    printui:
        build:
            context: ui/getNameUI
        ports:
            - "8080:80"
        environment:
            - API_GETNAME_NAME=getname_api
        depends_on:
            - getname_api
    insertui:
        build: 
            context: ui/insertNameUI
        ports: 
            - "8081:80"
        environment:
            - API_INSERTNAME_NAME=insertname_api
        depends_on: 
            - insertname_api
            
    getname_api:
        build:
            context: api/getNameAPI
        ports:
            - "8085:80"
        depends_on: 
            - db

    insertname_api:
        build: 
            context: api/insertNameAPI
        ports: 
            - "8086:80"
        depends_on: 
            - db
    db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
    
    dbvisualiser:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - "8082:80"
volumes: 
    dbdata: