ARG VERSION=apache

FROM php:${VERSION}

ARG TARGETPLATFORM=arm

RUN echo "Building for linux/$TARGETPLATFORM platform"

RUN sed -i '1s/^/ServerName localhost\n/' /etc/apache2/apache2.conf

COPY . /var/www/html/

EXPOSE 80