ARG VERSION=apache

FROM php:${VERSION}

ARG TARGETPLATFORM 

RUN echo "Building for $TARGETPLATFORM platform"

RUN sed -i '1s/^/ServerName localhost\n/' /etc/apache2/apache2.conf

COPY . /var/www/html/

EXPOSE 80